### ISSUE TITLE
Unable to Bind My SAP Project from BAS

### ISSUE THREAD

**Issue by Hemanth2491** [SAP-samples/cap-hana-exercises-codejam#19]
Hi All,
In exercise 3,step 3 Explore generated design-time artifacts tutorial
 when i tried to bind my project to a Database Connection and HDI container instance am not getting any popups but am getting 4 options 
1. Bind to an HDI Container( when clicking on this am getting error as NO HDI Shared plan available in space. However my DB Instance is up and running)
2. Bind to a user provided service( when clicking getting warning as No service instance is found)
3. Bind to a schema Service(  when clicking on this am getting error as NO HDI Shared plan available in space. However my DB Instance is up and running)
4. Bind to an application managed service( when clicking on this getting warning as Please create a service manager instance.)
 
Please help me to resolve this issue. Do i miss any configuration

![image](https://github.com/SAP-samples/cap-hana-exercises-codejam/assets/139891850/f5811d01-0e85-4388-bb60-26163b7a9b07)
![image](https://github.com/SAP-samples/cap-hana-exercises-codejam/assets/139891850/adac647d-157a-472c-ba5d-b6933ef960fb)

**Comment by jung-thomas** [comment]
If you have no HDI- shared plan than you are missing the entitlement in your sub-account.  Please add this entitlement. Are you using the free trial?  Normally this entitlement is added automatically in the free trial.  Did you manually create a second sub-account in your free trial global account?

**Comment by Hemanth2491** [comment]
Yes Jung i have created second sub-account. Now i have added SAP HANA Schemas & HDI Containers Entitlement.
Thanks for your quick response.

**Comment by Hemanth2491** [comment]
Hi Thomas,
I am getting error when i tried to create an service instance.
![image](https://github.com/SAP-samples/cap-hana-exercises-codejam/assets/139891850/0bba265a-91a5-49d7-ba0e-9b2d6bec663e)

**Comment by jung-thomas** [comment]
The tooling unfortunately sometimes doesn't wait long enough for the service and key to be created.  Wait a moment and try again.  Just bind to the existing service (which should show up in the list once it's created). You can also check the creation status from the terminal with the `cf services`.

**Comment by Hemanth2491** [comment]
Thanks Thomas
