### ISSUE TITLE
CF create-service xsuaa not able to read xs-security.json file

### ISSUE THREAD

**Issue by romi9035** [SAP-samples/cap-hana-exercises-codejam#8]
Hello,

I am getting below error while creating XSUAA service instance using xs-security.json file.

![image](https://user-images.githubusercontent.com/47141660/217613372-25d51ec6-1cdc-4688-ae73-63e5dccd1a78.png)

Without using -c xs-security.json file , service instance is getting created.
![image](https://user-images.githubusercontent.com/47141660/217613414-eb891478-5d76-49dc-ab12-ede2beb078d6.png)

using -c .\xs-security.json file is also not working.
![image](https://user-images.githubusercontent.com/47141660/217613638-f803daca-9e42-4957-a37b-61a1197dfb16.png)

Regards,
Romil A.

**Comment by jung-thomas** [comment]
Are you in a folder that has a file named xs-security.json?  And do you have correct JSON in this file. The command output is saying it doesn't like the file (my first thought was the path to it), but it could also be indicating a missing file or one with bad JSON in it as well.

**Comment by romi9035** [comment]
Yes, my folder contains xs-security.json file in the same path.

![image](https://user-images.githubusercontent.com/47141660/217618648-7c0be44e-93dd-49ac-9293-ed01cd1be1ca.png)

**Comment by romi9035** [comment]
> Yes, my folder contains xs-security.json file in the same path.
> 
> ![image](https://user-images.githubusercontent.com/47141660/217618648-7c0be44e-93dd-49ac-9293-ed01cd1be1ca.png)

**Comment by romi9035** [comment]
> ```json
> "xsappname": "myhanaapp2",
>     "tenant-mode": "dedicated",
>     "description": "Security profile of called application",
> ```

Thank you, Thomas for your valuable reply.
Probably something was wrong with the content of my previous file, but not sure what.
I just deleted the xs-security.json file and recreated using the command and it worked fine.

Regards,
Romil A.
